# this workflow will run on all pushes.
on:
  push:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

name: "push"
jobs:
  build-modules:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3.5.3
      -
        name: Regenerate modules.json
        run: node build_modules.js
      -
        name: Check for changes
        id: check_for_changes
        run: |
          if git diff --exit-code; then
            echo "All clear"
          else
            echo "changes in modules.json!"
            echo "Please run node build_modules.js"
            exit 1
          fi


  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v5
        if: github.ref == 'refs/heads/${{github.master_branch}}'
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
