# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:

  build-modules:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4.1.1
      -
        name: Regenerate modules.json
        run: node build_modules.js
      -
        name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "::set-env name=changes_exist::false"
          else
            echo "::set-env name=changes_exist::true"
          fi
      -
        name: Commit files
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git add modules.json
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Generated modules.json"
      -
        name: Push changes
        if: ${{ env.changes_exist == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true


  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v5
        if: github.ref == 'refs/heads/${{github.master_branch}}'
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
