# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:
  build-modules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4.1.6
      -
        name: Regenerate modules.json
        run: node build_modules.js
      -
        name: Check for changes
        id: check_for_changes
        run: |
          if git diff --exit-code; then
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          fi
      -
        name: Commit files
        if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
        run: |
          git add modules.json
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Generated modules.json"
      -
        name: Push changes
        if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v6
        if: github.ref == 'refs/heads/${{github.master_branch}}'
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
